{
    'name': 'Soy Ambiental - Base',
    'description': 'Módulo base de Soy Ambiental',
    'summary': 'Módulo base de Soy Ambiental',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'version': '18.0.1.0.0',
    'license': 'Other proprietary',
    'category': 'soyambiental',
    'depends': [
        'hola_calidad',
        'mgmtsystem_process',
        'mgmtsystem_employees',
        'mgmtsystem_context',
        'mgmtsystem_qualitymanual',
        'mgmtsystem_opportunity',
        'mgmtsystem_legal',
        'mgmtsystem_context',
        'mgmtsystem_comunication',
        'mgmtsystem_infrastructure',
        'mgmtsystem_target',
        'mgmtsystem_audit',
        'mgmtsystem_management_review',
        'mgmtsystem_nonconformity',
        'mgmtsystem_action',
        'soyseguridad_contigency_plan',
    ],
    'data': [
        'security/security.xml',
        'views/menus.xml',
    ],
    'auto_install': False,
    'application': True,
}
